name: Hub Merged Rewards

on:
  schedule:
    # IST to UTC conversion (IST = UTC + 5:30)
    # 10:00 AM IST = 04:30 UTC
    - cron: '30 4 * * *'
    # 11:00 AM IST = 05:30 UTC
    - cron: '30 5 * * *'
    # 04:00 PM IST = 10:30 UTC
    - cron: '30 10 * * *'
    # 06:00 PM IST = 12:30 UTC
    - cron: '30 12 * * *'
  
  workflow_dispatch: # Allows manual run

jobs:
  run-merged-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Merged Rewards Script
        run: python hub_merged_rewards_updated.py
