name: Hub Progression Rewards

on:
  schedule:
    # Runs at 6:00 AM IST (00:30 UTC)
    - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  run-progression:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Tools
        run: |
          pip install -r requirements.txt

      - name: Run Script & Save Output
        run: python 2_hub_ProgressionProgram_rewards_updated.py > progression_log.txt
      
      - name: Show Output
        if: always()
        run: cat progression_log.txt

      - name: Send Email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Progression Rewards Status
          body: file://progression_log.txt
          to: ${{ secrets.MAIL_USERNAME }}
          from: Rewards Bot
