name: Hub Progression Rewards

on:
  schedule:
    # IST = UTC +5:30
    # 08:00 PM IST = 14:30 UTC
    - cron: "30 14 * * *"
    # 08:30 PM IST = 15:00 UTC
    - cron: "0 15 * * *"
    # 09:00 PM IST = 15:30 UTC
    - cron: "30 15 * * *"
    # 09:30 PM IST = 16:00 UTC
    - cron: "0 16 * * *"
  workflow_dispatch:  # Allows manual run

jobs:
  run-progression-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Progression Rewards Script
        run: python g_hub_ProgressionProgram_rewards_updated.py

      - name: Send success email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "✅ Hub Progression Rewards Job Successful"
          to: ${{ secrets.SMTP_TO }}
          from: ${{ secrets.SMTP_FROM }}
          content_type: text/plain
          body: |
            The **Hub Progression Rewards** script ran successfully.
            Repository: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Workflow: ${{ github.workflow }}
            Run #: ${{ github.run_number }}

      - name: Send failure email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "❌ Hub Progression Rewards Job Failed"
          to: ${{ secrets.SMTP_TO }}
          from: ${{ secrets.SMTP_FROM }}
          content_type: text/plain
          body: |
            The **Hub Progression Rewards** script failed.
            Repository: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Workflow: ${{ github.workflow }}
            Run #: ${{ github.run_number }}
            Please check the Actions logs for details.
