name: Hub Daily Rewards

on:
  schedule:
    - cron: "0 6 * * *"    # 11:30 AM IST
    - cron: "0 13 * * *"   # 6:30 PM IST
  workflow_dispatch:

jobs:
  run-daily-rewards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run script and email log
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          python send_email_with_log.py hub_daily_rewards.py "Hub Daily Rewards"
