name: Hourly Rewards Claimer

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run-claimer:
    runs-on: ubuntu-latest
    timeout-minutes: 130

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Script
        run: python master_claimer.py
